### ISSUE TITLE
Memory leak issue on nitemp

### ISSUE THREAD

**Issue by ksmith0** [ksmith0/PixieSuite#20]
When trying run a seg fault occurs that appears to be in StatsHandler::Dump()

**Comment by ksmith0** [comment]
Commit 3801559c192fd884b8a5fc143e5c67d0c1fd670c seems stable.

**Comment by ksmith0** [comment]
The issue appears in commit f4c1987580cd3e416101048368232f037582624c.

**Comment by ksmith0** [comment]
Specifically the issue is related to the change to poll2_core.cpp in commit f4c1987.

**Comment by cthornsb** [comment]
Yes, changing char array "packet" back to a variable length array fixes this issue.

**Comment by ksmith0** [comment]
This code is not is compliance with the C++ standard, but when following the standard the code does not work as expected. We need to confirm if just rolling back f4c1987 resolves all the issues. We also observed issues with get_traces.

Perhaps for now we remove the pedantic flag.

**Comment by ksmith0** [comment]
This issue was resolved in commit 203991ab00ce190bbaab6a1ab17362751578cec5

**Comment by ksmith0** [comment]
This issue was moved to pixie16/PixieSuite2#42
