### ISSUE TITLE
hribf Data Buffer has more than 8194 words

### ISSUE THREAD

**Issue by ksmith0** [ksmith0/PixieSuite#22]
After a file rollover it was noticed that data could no longer be scanned. Stopping and starting a new run did not resolve the issue. Poll had to be restarted.

The corrupted files have more than 8194 words in the data buffer. @cthornsb Do you have any idea how the data buffer could be written this large?

**Comment by cthornsb** [comment]
The actual size of the buffers is still 8194.  This is just an error in the way I count the words.  Old files do the same thing.  The words > 8194 is just a warning and doesn't actually do anything.  I've confirmed this with HexReader.

**Comment by ksmith0** [comment]
Two files from the 19F(a,n) experiment were observed with the first buffer size of 8212.

**Comment by cthornsb** [comment]
I can't reproduce this on rg2gx280 with a 1 kHz pulser in channel 0, 0 and the maximum file size changed to 10 MB. Iterated through 1 standard file and 5 rollover files with no complaints from poll2 or PixieLDf.  Confirmed with HexReader.

**Comment by cthornsb** [comment]
Reproduced issue on nitemp even during standard data taking (not after rollover). First corrupt file and all subsequent files had overfilled first DATA buffers. Scanor is unable to scan corrupted files. Restarting poll2 seems to "fix" the issue.

**Comment by cthornsb** [comment]
Poll2 does not need to be restarted to fix this error. The over filled buffers seem to be a side effect of a very large rate.  Lowering the rate fixes the problem.

**Comment by ksmith0** [comment]
This issue was moved to pixie16/PixieSuite2#45
