### ISSUE TITLE
quiet command not recognized

### ISSUE THREAD

**Issue by spaulaus** [ksmith0/PixieSuite#32]
I have pulled a fresh copy from the repo and found that the "quiet" option is not recognized. 

![quietpic](https://cloud.githubusercontent.com/assets/1553042/9875754/c1d60fe2-5b7e-11e5-9ab7-38f4114b57aa.png)

**Comment by ksmith0** [comment]
Resolved in commit f5e60ab8f80d7f67103030813fda9538271a742f

**Comment by ksmith0** [comment]
This issue was moved to pixie16/PixieSuite2#52
