### ISSUE TITLE
Buffer size too big

### ISSUE THREAD

**Issue by wapmanzoo** [ksmith0/PixieSuite#36]
On the NiTemp computer using the master version of PixieSuite, the buffer sizes are larger than the normal 8194 words. This causes pixie-scan to abort after the first buffer.

**Comment by ksmith0** [comment]
This should be reported at [pixie16/PixieSuite2](https://github.com/pixie16/PixieSuite2/issues)

**Comment by ksmith0** [comment]
Closing issue as development has moved to the @pixie16 group.
