### ISSUE TITLE
ouf with no arguments.

### ISSUE THREAD

**Issue by ksmith0** [ksmith0/PixieSuite#8]
It would be nice to have an option to output the name of the current open ldf file. I expected ouf with no argument to do this, but I simply get the message "Set output file name to ''". It is unclear to me what the result is the resulting action of this command.

**Comment by cthornsb** [comment]
The "ouf" command, along with "fdir, "htit", "hnum", "oform", and "stats", no longer attempts to set a value if passed a blank string as an argument.  Instead, they will now output the current value to the screen. This feature was added in commit b858172.

**Comment by ksmith0** [comment]
This issue was moved to pixie16/PixieSuite2#30
